# Generated by Django 4.2.30 on 2026-04-17 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('location', models.CharField(choices=[('Outdoor Garden Venue', 'Outdoor Garden Venue'), ('Luxury Hotel Ballroom', 'Luxury Hotel Ballroom'), ('Beachside Pavilion', 'Beachside Pavilion'), ('Rooftop Terrace', 'Rooftop Terrace'), ('Heritage Haveli', 'Heritage Haveli'), ('Community Hall', 'Community Hall')], max_length=100, verbose_name='Venue')),
                ('decoration', models.CharField(choices=[('Floral Fantasy', 'Floral Fantasy'), ('Fairy Lights & Drapes', 'Fairy Lights & Drapes'), ('Royal Gold & Red', 'Royal Gold & Red'), ('Minimalist Modern', 'Minimalist Modern'), ('Boho & Rustic', 'Boho & Rustic')], max_length=100, verbose_name='Decoration Style')),
                ('food', models.CharField(choices=[('Veg Buffet (100 pax)', 'Veg Buffet (100 pax)'), ('Non-Veg Buffet (100 pax)', 'Non-Veg Buffet (100 pax)'), ('Multi-Cuisine (100 pax)', 'Multi-Cuisine (100 pax)'), ('Dessert & Snacks Bar', 'Dessert & Snacks Bar'), ('Live Food Stations', 'Live Food Stations')], max_length=100, verbose_name='Catering Option')),
                ('extras', models.TextField(blank=True, help_text='Comma-separated list of extra services selected', verbose_name='Additional Services')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost (₹)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
